eplApp.config(['$routeProvider',function($routeProvider) {
	$routeProvider
	.when('/',{
		templateUrl:'views/index-view.html',
		controller:'displayallmatchescontroller',
		controllerAs:'displaymatch'
	})
	.when('/15/:date/:team1/:team2',{
		templateUrl:'views/single-match-view.html',
		controller:'displaysinglematch',
		controllerAs:'singlematch'
		})
	.when('/16/:date/:team1/:team2',{
		templateUrl:'views/single-match16-view.html',
		controller:'displaysinglematch16',
		controllerAs:'singlematch'
		})
	.when('/1516',{
		templateUrl:'views/team1516-view.html',
		controller:'displayallmatchescontroller',
		controllerAs:'team1516'
		})
	.when('/1617',{
		templateUrl:'views/team1617-view.html',
		controller:'displayallmatchescontroller',
		controllerAs:'team1617'
		})
	.when('/team1516/:team',{
		templateUrl:'views/teamstat15-view.html',
		controller:'displayteamstat15controller',
		controllerAs:'teamstat1516'
		})
	.when('/team1617/:team',{
		templateUrl:'views/teamstat16-view.html',
		controller:'displayteamstat16controller',
		controllerAs:'teamstat1617'
		})
	.otherwise(
            {
                //redirectTo:'/'
                template   : '<h1>404 page not found</h1>'
            }
        );
}])